### PR TITLE
Added alternate spellings to answers

### PR DESCRIPTION
**Pull request by mrfizzl3**
Added alt. answers and fixed a spelling error.

### CODE REVIEW

**Comment by MiniJennJenn** [comment]
I'm not sure how I feel about accepting what's technically a misspelling (FedEx Forum). But I guess it'll be ok to be a little forgiving.

**Comment by mrfizzl3** [comment]
LOL. I know it's a misspelling but others may know the name but not how to space (or not to space) the words. I can remove it if you'd like.

**Comment by palmtree5** [comment]
Just for future reference, PR to `develop` instead of `master`. We're only merging to `master` for releases

**Comment by palmtree5** [comment]
The tests are failing on this because "the list failed to load" (though it's not quite apparent why)

**Comment by mrfizzl3** [comment]
Hopefully this fixes it.

**Comment by mrfizzl3** [comment]
It passed! And I'll make sure to use develop from now on. Sorry about that @MiniJennJenn

**Pull request merged**
